In [78]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.cluster import KMeans
from os import listdir
from os.path import isfile, join
import matplotlib.pyplot as plt
from scipy import stats
from sklearn import metrics
import csv
import keras
import keras.utils
from keras import utils as np_utils


In [79]:
from tensorflow.keras import regularizers
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, ZeroPadding2D
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam, SGD

In [80]:
'''
img2 = cv2.drawKeypoints(image1,kps,None,(255,0,0),4)
plt.imshow(img2),plt.show
'''

'\nimg2 = cv2.drawKeypoints(image1,kps,None,(255,0,0),4)\nplt.imshow(img2),plt.show\n'

In [81]:


images_path = '/home/navya/Documents/sjsu/project-257/dataset-resized/dataset-resized'

# CARDBOARD = 0 GLASS = 1 METAL = 2 PAPER = 3 PLASTIC = 4 TRASH = 5
types = ['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']

files = []
labels = []
for i, each_type in enumerate(types):
    path = join(images_path, each_type) 
    for f in listdir(path):
        file_path = join(path, f)
        if isfile(file_path):
            files.append(file_path)
            labels.append(i)

images = np.empty(len(files), dtype=object)
for i in range(len(files)):
    images[i] = cv2.imread(files[i], 0)
    images[i] = cv2.normalize(images[i], None, 0, 255, cv2.NORM_MINMAX)
    (kps, descs) = surf.detectAndCompute(images[i], None)
    
from sklearn.model_selection import train_test_split
images_train, images_test, y_train, y_test = train_test_split(images,labels, test_size=0.1, random_state=42)




In [82]:
def to_surf_desc(image):
    (kps, descs) = surf.detectAndCompute(np.array(image), None)
    #print (type(descs))
    #print (descs.shape)
    if descs is None:
        return np.empty((1, 64))
    return descs
    
image_surf_train = [to_surf_desc(image) for image in images_train]
image_surf_test = [to_surf_desc(image) for image in images_test]

print (image_surf_train)
#print("kps : {}, descriptors : {}".format(len(kps), descs.shape))

[array([[ 3.9624819e-03,  6.8669603e-04,  4.0736739e-03, ...,
         1.1241601e-03,  4.0163645e-03,  1.6296776e-03],
       [ 5.4778815e-03,  7.1314449e-04,  6.2431186e-03, ...,
         8.0490179e-05,  8.4682967e-04,  1.7267279e-04],
       [-3.4810477e-03,  4.4117838e-05,  4.7246637e-03, ...,
        -2.6910095e-03,  3.1044376e-03,  3.8286941e-03],
       ...,
       [ 7.7148713e-04, -6.3393428e-04,  2.7253560e-03, ...,
         1.9918475e-04,  4.6927575e-03,  4.7506826e-04],
       [ 8.8908558e-04, -2.8438761e-04,  4.1531823e-03, ...,
        -3.8354262e-03,  6.9671776e-03,  5.4605980e-03],
       [-3.9016725e-03,  4.8103282e-04,  1.0759989e-02, ...,
        -9.6737588e-04,  1.0668145e-02,  1.6570491e-03]], dtype=float32), array([[ 2.9796528e-04, -3.2855800e-04,  4.8725193e-04, ...,
         1.2747626e-03,  8.3848613e-04,  1.7747704e-03],
       [ 3.4485289e-04, -3.6196259e-04,  5.1531522e-04, ...,
         1.3956258e-03,  9.6401927e-04,  1.8097714e-03],
       [-5.3371158e-03,  2

In [83]:
print (len(image_surf_train))
for each in image_surf_train:
    print (each)
#print (image_surf_train[1][0])

2274
[[ 3.9624819e-03  6.8669603e-04  4.0736739e-03 ...  1.1241601e-03
   4.0163645e-03  1.6296776e-03]
 [ 5.4778815e-03  7.1314449e-04  6.2431186e-03 ...  8.0490179e-05
   8.4682967e-04  1.7267279e-04]
 [-3.4810477e-03  4.4117838e-05  4.7246637e-03 ... -2.6910095e-03
   3.1044376e-03  3.8286941e-03]
 ...
 [ 7.7148713e-04 -6.3393428e-04  2.7253560e-03 ...  1.9918475e-04
   4.6927575e-03  4.7506826e-04]
 [ 8.8908558e-04 -2.8438761e-04  4.1531823e-03 ... -3.8354262e-03
   6.9671776e-03  5.4605980e-03]
 [-3.9016725e-03  4.8103282e-04  1.0759989e-02 ... -9.6737588e-04
   1.0668145e-02  1.6570491e-03]]
[[ 2.9796528e-04 -3.2855800e-04  4.8725193e-04 ...  1.2747626e-03
   8.3848613e-04  1.7747704e-03]
 [ 3.4485289e-04 -3.6196259e-04  5.1531522e-04 ...  1.3956258e-03
   9.6401927e-04  1.8097714e-03]
 [-5.3371158e-03  2.0541192e-03  6.0342308e-03 ...  2.2713211e-05
   8.1272400e-04  7.0366997e-04]
 ...
 [-1.4012752e-03 -1.2298090e-03  2.0733248e-03 ...  2.3766609e-03
   8.8089891e-03  6.7909714

   8.4771132e-03  1.1083225e-03]]
[[-1.5747739e-03  2.3252556e-04  3.6961602e-03 ...  3.4757552e-04
   7.8240508e-04  3.5817799e-04]
 [-5.1359570e-04  8.4664985e-05  7.6948968e-04 ...  3.5273016e-04
   3.5168495e-04  3.6849026e-04]
 [-1.7368799e-04 -1.5254829e-04  3.1831252e-04 ...  5.9148506e-03
   6.0647068e-04  6.0583283e-03]
 ...
 [-1.8798210e-02 -6.9939363e-04  1.9429397e-02 ... -3.0477555e-04
   3.8911079e-04  8.9354493e-04]
 [-1.4973434e-02  4.0216581e-03  1.5246036e-02 ... -6.3348678e-04
   9.5737877e-04  6.3348678e-04]
 [ 4.4935982e-04  2.5081297e-04  1.0082038e-03 ...  1.0914255e-03
   5.9381098e-04  1.0914255e-03]]
[[ 0.00542537 -0.00155421  0.00638044 ... -0.00056159  0.00026592
   0.0006217 ]
 [ 0.00130576 -0.0003222   0.00406836 ... -0.00048051  0.00040482
   0.00069419]
 [ 0.00221477 -0.00031133  0.00320169 ... -0.00041559  0.00023083
   0.00041559]
 ...
 [-0.00866614 -0.01231252  0.00871867 ...  0.00047404  0.0011514
   0.00125927]
 [ 0.00160466  0.00058233  0.00289121 

[[-1.0790448e-03  1.2241879e-03  1.5616565e-03 ... -1.9120738e-03
   3.0687705e-03  3.4853006e-03]
 [ 2.8416247e-03  4.2856671e-03  3.7869860e-03 ...  1.4951342e-03
   3.5628271e-03  1.7259651e-03]
 [ 6.6177892e-03  2.0092980e-03  6.6375528e-03 ...  8.5476821e-04
   9.7752060e-04  2.6598107e-03]
 ...
 [-6.4908038e-03 -4.9201455e-03  1.0814162e-02 ... -3.7501781e-04
   1.1224372e-02  2.1910216e-03]
 [ 5.3009346e-02  6.1358995e-04  5.3009346e-02 ...  1.4552202e-04
   3.5864789e-02  2.0364244e-03]
 [-1.1810566e-03  4.6793789e-06  3.2353292e-03 ...  6.3805113e-04
   1.6049445e-03  9.5772615e-04]]
[[-2.43039639e-03  1.24409515e-03  9.12823062e-03 ...  1.16959134e-04
   2.45538802e-04  1.16959134e-04]
 [ 3.97913711e-04 -1.29925413e-03  3.97913711e-04 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.07144369e-02 -3.59919877e-03  1.07144369e-02 ... -5.16347936e-04
   1.33908784e-03  5.16347936e-04]
 ...
 [-5.27903112e-03 -8.03989940e-04  5.92175731e-03 ... -6.89988010e-05
   1.37139

   2.88725477e-02  1.65361278e-02]]
[[ 6.4947782e-04  1.6454206e-03  6.6131185e-04 ... -5.0170049e-05
   1.8920995e-04  5.3096323e-05]
 [-7.2314334e-04  1.0322388e-03  7.2314334e-04 ... -1.4076212e-04
   6.8957146e-05  1.4076212e-04]
 [-5.9142278e-04  8.1736321e-04  6.6759379e-04 ... -3.3090308e-03
   1.2784756e-03  3.3090308e-03]
 ...
 [ 3.3886102e-04 -3.9981685e-05  3.3886102e-04 ... -7.8523830e-05
   2.8314147e-02  1.1764232e-03]
 [ 7.7519962e-03 -9.6859329e-04  8.7513458e-03 ...  6.8026833e-04
   2.1788315e-03  1.2042328e-03]
 [-1.1350609e-05 -1.2261537e-05  1.4157391e-05 ...  8.8189996e-04
   9.9107157e-04  9.4421220e-04]]
[[-2.1356153e-03 -8.4440550e-03  2.9447929e-03 ...  3.4595374e-04
   2.5937695e-03  5.3141703e-04]
 [-2.1753833e-04  1.8405776e-04  3.4515490e-04 ... -3.1941329e-04
   7.2842761e-04  3.6705821e-04]
 [ 1.3166737e-04  1.7582708e-03  2.0304098e-04 ...  3.1048228e-05
   5.5195641e-04  1.2785199e-04]
 ...
 [ 2.3540093e-03 -2.9114848e-05  5.2954182e-03 ... -2.1724100e

   1.2726141e-03  5.7888939e-04]]
[[-3.17689701e-04 -6.97597570e-04  6.58446981e-04 ...  3.18052922e-03
   7.06512667e-03  3.67821800e-03]
 [-1.61378435e-03 -8.58468062e-04  4.93780477e-03 ...  5.72918332e-04
   9.07234941e-03  4.63014422e-03]
 [-7.37873081e-04  1.31314516e-03  2.98573752e-03 ... -2.15280561e-05
   5.19459788e-03  3.61848017e-03]
 ...
 [-6.58339448e-03  1.03036640e-03  1.12325232e-02 ...  1.40844595e-05
   8.80035048e-04  5.51493176e-05]
 [ 4.58099646e-04  6.42065250e-04  8.17242311e-04 ...  8.88790055e-06
   2.75811297e-04  8.88790055e-06]
 [ 2.27751280e-03  1.63981225e-04  7.15271616e-03 ... -2.19211448e-02
   1.53807849e-02  4.15367782e-02]]
[[ 2.93364301e-05 -2.32071943e-05  4.17159245e-05 ... -9.63789716e-05
   1.01462989e-04  9.63789716e-05]
 [-3.37277335e-04  5.28333418e-04  1.57216948e-03 ... -1.15018251e-04
   9.15718920e-06  1.15018251e-04]
 [-2.86699459e-03  4.75961104e-04  3.68532096e-03 ...  1.41711251e-04
   1.07586086e-04  1.44265461e-04]
 ...
 [-2.31687

   2.4037582e-03  7.1713910e-04]]
[[ 5.1412691e-05 -4.7084474e-04  7.4301043e-04 ...  4.4578428e-05
   2.4338481e-03  2.0584329e-04]
 [ 6.5944195e-03  1.1465867e-03  6.5946607e-03 ...  1.5343438e-04
   5.4164985e-03  2.2050021e-03]
 [ 5.1108535e-05  4.7185295e-05  1.0177063e-04 ... -6.1120947e-05
   3.5365862e-05  6.4529675e-05]
 ...
 [ 2.1025268e-03  5.5913412e-04  3.4478474e-03 ... -5.6044581e-05
   1.5982121e-04  1.8084617e-04]
 [-5.4697152e-03 -1.5716100e-04  9.5828800e-03 ... -2.9874052e-04
   5.8095949e-03  1.7710698e-03]
 [ 4.9953982e-03  1.2470097e-03  4.9953982e-03 ...  1.5279093e-05
   1.4261789e-04  1.1183893e-04]]
[[-0.0026935   0.00034747  0.00949244 ... -0.00123829  0.00392937
   0.00129375]
 [-0.00139601 -0.00548787  0.00287071 ... -0.00065289  0.00538883
   0.00135343]
 [ 0.00170816 -0.00058995  0.00339935 ...  0.00075378  0.00097755
   0.00098098]
 ...
 [-0.00098697  0.00021564  0.00386139 ...  0.00192331  0.01658051
   0.00343674]
 [-0.00119982  0.00127062  0.00234028

   0.00030588]]
[[-2.8659558e-04  9.7818098e-05  3.4547009e-04 ... -1.0470917e-03
   3.1651899e-03  1.0519206e-03]
 [-2.3761527e-04 -3.1144972e-04  3.8363799e-04 ... -4.5505078e-03
   6.4705228e-03  4.5860521e-03]
 [-4.1485424e-03  7.1631611e-04  4.1485424e-03 ... -3.9828581e-05
   1.4047090e-04  8.6337437e-05]
 ...
 [-7.7313569e-04 -1.5901665e-03  1.1120461e-03 ... -1.4871242e-02
   8.6356066e-03  1.6698733e-02]
 [-2.8100195e-03 -5.3180073e-04  2.8100195e-03 ...  4.3138320e-04
   2.8817265e-03  1.1138036e-03]
 [-2.7674804e-03 -5.7004497e-04  2.8102396e-03 ...  1.0042158e-03
   2.4154282e-03  1.9756574e-03]]
[[ 0.00696407 -0.00159798  0.01499156 ... -0.00109633  0.00055745
   0.00165909]
 [-0.0011744  -0.00095028  0.00241543 ... -0.00086     0.00067116
   0.00118113]
 [-0.00501832  0.00128756  0.00521766 ... -0.00021641  0.00091917
   0.00077714]
 ...
 [-0.00176938  0.0007047   0.00279584 ... -0.00106974  0.00191085
   0.00129927]
 [-0.00057411 -0.00350725  0.00697048 ... -0.00307013  

   1.18431650e-04  2.76878098e-04]]
[[-0.00219588 -0.00063695  0.00695696 ...  0.00102714  0.00645379
   0.00336402]
 [ 0.01406484  0.0031517   0.01476302 ... -0.00172778  0.0023782
   0.00260978]
 [ 0.00044538 -0.00085986  0.0004614  ... -0.00416388  0.00788188
   0.00814395]
 ...
 [ 0.00067178  0.00066907  0.00170948 ... -0.0004677   0.0018978
   0.00054222]
 [ 0.008688   -0.00683639  0.00930407 ... -0.0004781   0.00041003
   0.00061755]
 [ 0.00303298 -0.00559846  0.00412319 ... -0.00051729  0.00021898
   0.00052147]]
[[ 1.6448221e-03 -7.0280978e-03  1.9400845e-03 ... -1.1585162e-03
   1.1176147e-03  1.7077144e-03]
 [ 1.6608213e-03 -7.0797326e-03  1.9756579e-03 ... -1.1487699e-03
   1.1087336e-03  1.7003166e-03]
 [ 5.6740869e-04  8.0554993e-05  5.6740869e-04 ...  3.7595842e-04
   6.8142838e-03  2.8262425e-03]
 ...
 [-1.5600922e-03 -1.1134980e-04  2.9068731e-03 ...  9.8313869e-04
   3.4343445e-04  9.9300616e-04]
 [-1.0949527e-03 -3.9905687e-03  4.9785990e-03 ... -3.7924841e-03
   7.89

   2.1300535e-03  2.0047335e-03]]
[[ 3.5991316e-04 -1.2915766e-04  7.1065850e-04 ...  4.0279992e-04
   2.1416879e-04  4.0279992e-04]
 [-1.6410999e-02 -6.7677360e-04  1.6410999e-02 ... -4.7374357e-04
   5.0441682e-04  4.7703020e-04]
 [-1.6655398e-03  1.6194044e-03  4.1957865e-03 ... -7.8480203e-05
   3.2198033e-04  1.6071889e-04]
 ...
 [-1.2994257e-03 -8.4044825e-04  1.2994257e-03 ... -1.0314211e-02
   9.7933216e-03  1.0599595e-02]
 [ 1.1519803e-03 -3.1082117e-04  1.1519803e-03 ... -1.0546510e-03
   5.1979795e-03  3.2209419e-03]
 [-1.3276898e-04 -1.1927218e-03  1.4350838e-03 ... -4.2328727e-03
   7.5360769e-03  4.4555049e-03]]
[[-3.5592917e-04  1.4475756e-04  9.8987692e-04 ...  1.9627879e-04
   1.1911275e-03  6.8249227e-04]
 [-1.4325231e-03  1.1809637e-05  1.5693288e-03 ...  3.9859756e-04
   1.8376847e-03  8.9014822e-04]
 [-3.0198117e-04  4.1891049e-04  1.5751359e-03 ... -1.9488148e-04
   1.3904622e-03  2.8592772e-03]
 ...
 [ 3.9388095e-03 -1.0786721e-02  1.5568511e-02 ...  6.2208972e-0

   0.0018011 ]]
[[-3.4440894e-04 -1.6399475e-03  7.4001111e-04 ...  4.2187073e-03
   2.0765073e-03  6.6933660e-03]
 [-8.9149602e-05 -3.8980117e-05  1.3317386e-04 ... -9.3475176e-04
   1.1606317e-02  3.0241753e-03]
 [ 3.6972904e-04 -1.5908489e-03  6.9471321e-04 ...  3.0524598e-03
   1.9014814e-03  3.6309990e-03]
 ...
 [ 1.7890848e-04 -2.7232561e-03  9.3491469e-04 ...  3.9713876e-03
   9.4630076e-03  3.9713876e-03]
 [ 2.3052903e-04 -9.5824216e-05  2.4146760e-04 ... -7.1570459e-05
   8.8843837e-05  7.3821720e-05]
 [-3.0345292e-04 -4.2829342e-06  3.0345292e-04 ...  6.1652150e-05
   8.6817781e-05  7.0918693e-05]]
[[-9.3063823e-04 -6.4334262e-04  9.6523704e-04 ...  8.8552141e-04
   2.3456591e-03  8.9386379e-04]
 [-3.6092231e-06  1.3818830e-03  1.2271691e-04 ...  2.7998385e-04
   1.8899643e-04  3.1863485e-04]
 [-1.2573138e-03  1.2976759e-04  1.4290034e-03 ...  6.9654302e-04
   6.8602239e-04  9.9150278e-04]
 ...
 [-2.8627520e-04 -9.5706651e-05  3.8507732e-04 ... -8.5780479e-04
   2.5415560e-03

   6.9736211e-06  4.7092603e-06]]
[[ 2.2340628e-04  8.9390851e-05  3.4191128e-04 ... -2.6432303e-04
   9.3977811e-05  3.0813133e-04]
 [ 7.6357581e-05  4.3020911e-05  1.6796950e-04 ... -1.4318432e-05
   1.9098861e-04  1.0046210e-04]
 [-5.0200988e-04  4.0207771e-05  6.6490233e-04 ...  3.7683023e-04
   1.4074090e-03  5.2039936e-04]
 ...
 [ 1.4192556e-03 -8.3699997e-04  2.0457772e-03 ... -2.7070520e-04
   2.8876045e-03  4.0024452e-04]
 [-9.6269324e-03 -4.1229988e-04  1.3848653e-02 ... -5.6207489e-04
   6.0776970e-04  5.6492636e-04]
 [-7.8416680e-04 -8.4468233e-04  8.0546824e-04 ... -1.0546335e-03
   1.3438874e-03  1.0546335e-03]]
[[ 7.90333143e-04  2.30335770e-03  8.13920575e-04 ...  8.32598365e-04
   3.18728783e-03  9.76114126e-04]
 [-2.17071269e-03  1.26391603e-03  2.71553500e-03 ... -1.83574727e-03
   5.85940084e-04  1.83574727e-03]
 [-5.92824506e-07 -7.10037246e-04  1.68250946e-04 ...  5.05954085e-04
   1.20513956e-04  5.05954085e-04]
 ...
 [ 7.98773952e-04 -2.74564576e-04  5.28867682e

[[ 0.00179228 -0.00042034  0.002716   ... -0.00101276  0.00443691
   0.00281718]
 [-0.01003529 -0.00069855  0.01003529 ...  0.00035295  0.00033617
   0.00047202]
 [-0.00020986 -0.00482341  0.00211758 ... -0.00112531  0.00030011
   0.00112952]
 ...
 [ 0.00359579 -0.00622004  0.00534124 ... -0.00411127  0.00388895
   0.00845241]
 [ 0.00477462 -0.00122117  0.01072847 ...  0.00285096  0.01183078
   0.00374862]
 [ 0.00604017  0.01674835  0.00989239 ... -0.00230702  0.02129195
   0.0182156 ]]
[[ 5.8883266e-04  3.0062950e-04  1.0521541e-03 ... -6.4507744e-04
   2.7689787e-03  9.1086980e-04]
 [ 1.9782844e-04  1.0531900e-03  1.7490047e-03 ...  2.1487456e-03
   3.8126518e-03  4.9490170e-03]
 [-2.1084021e-03 -5.3611915e-03  2.6365151e-03 ... -1.5166133e-03
   8.1564588e-03  2.6300892e-03]
 ...
 [-2.3459201e-04 -6.2358947e-03  1.5035410e-02 ...  1.5239811e-03
   1.3871453e-02  6.5128831e-03]
 [ 2.2983775e-02  9.8870799e-04  2.6616158e-02 ... -4.5081569e-04
   4.5369784e-04  4.5081569e-04]
 [-6.167

   1.77912693e-03  8.83938221e-04]]
[[-2.8672870e-04 -8.0100987e-03  1.2379413e-03 ... -3.9250407e-04
   5.5883656e-04  4.9373135e-04]
 [ 3.3171917e-04 -2.7906417e-04  5.8813125e-04 ... -6.3262711e-04
   1.4963448e-04  1.2660656e-03]
 [-3.5904476e-04  6.6948496e-04  5.7764939e-04 ...  1.4108840e-05
   1.1115808e-03  6.3156214e-04]
 ...
 [ 1.8179155e-03  4.9693818e-04  3.8204209e-03 ... -6.1528194e-03
   1.5521536e-02  2.4834255e-02]
 [ 6.0629427e-05  3.1692491e-04  3.1625680e-04 ...  6.0160473e-05
   6.0262205e-04  3.9293236e-04]
 [-3.1438712e-03  1.6621028e-03  5.9661013e-03 ...  2.1854921e-03
   7.3009185e-03  8.8117346e-03]]
[[ 0.00555197 -0.00035599  0.00729198 ... -0.00103242  0.00316859
   0.0019362 ]
 [ 0.00425744 -0.00260335  0.00692799 ... -0.00050816  0.0036644
   0.00129352]
 [-0.00229731 -0.0021853   0.00567763 ...  0.00023866  0.00022715
   0.00023866]
 ...
 [-0.00059843  0.00104627  0.00319995 ...  0.00063774  0.01070217
   0.00192799]
 [ 0.00162018 -0.00306579  0.0083586

[[ 9.1124827e-04  3.7137638e-03  1.2578623e-03 ... -1.4002121e-04
   8.6834712e-05  1.5917412e-04]
 [ 2.7540447e-03 -3.4102242e-04  2.7540447e-03 ...  3.7487710e-04
   2.1839916e-04  3.7701285e-04]
 [-1.3198430e-03  3.8060227e-03  3.9553759e-03 ...  2.0932599e-03
   1.1338516e-03  2.1781416e-03]
 ...
 [-2.0513667e-03 -5.8729611e-03  3.9351559e-03 ... -4.9247718e-03
   6.1932858e-04  4.9247718e-03]
 [ 2.2557103e-03  1.3511362e-03  2.2857427e-03 ... -9.4703486e-04
   1.6231309e-03  5.4022660e-03]
 [-4.3552094e-03 -1.9702571e-04  5.9236763e-03 ...  5.2924825e-05
   8.3270064e-03  2.2205522e-03]]
[[ 1.4206656e-04 -1.7985977e-04  1.7828844e-04 ... -2.0135804e-04
   9.2295704e-05  2.3686260e-04]
 [ 4.8912170e-05 -2.2061527e-05  1.4746614e-04 ... -1.3498434e-04
   8.7186578e-05  1.5450326e-04]
 [ 2.0230780e-03 -4.1294089e-03  3.7384718e-03 ...  7.9629794e-03
   2.7416595e-03  7.9845097e-03]
 ...
 [-1.8369103e-02 -2.6079889e-03  1.9581148e-02 ... -8.6394092e-04
   5.9110569e-03  4.2384132e-03]

[[-9.5306488e-04  8.5280582e-05  1.4926186e-03 ...  3.2704510e-04
   4.6063699e-03  8.2938070e-04]
 [ 3.6958864e-04 -4.0815986e-04  4.6459908e-04 ... -1.6831417e-04
   1.7844766e-04  2.1044730e-04]
 [-5.7117594e-03 -5.4201782e-03  5.9606987e-03 ... -1.5099992e-03
   1.2215270e-03  1.5150473e-03]
 ...
 [-1.0418436e-03  1.2479557e-03  1.4340292e-03 ...  8.4529130e-04
   2.7998423e-03  8.7343756e-04]
 [ 2.3290848e-03 -2.5077240e-04  5.6154733e-03 ... -2.8876157e-04
   2.2475009e-03  5.7385000e-04]
 [-1.4589216e-02 -3.3231813e-03  1.4627613e-02 ... -3.1043761e-05
   8.3857235e-03  6.2710571e-04]]
[[ 0.00180747  0.00024417  0.00193785 ... -0.00096194  0.00081579
   0.00096194]
 [ 0.00121879 -0.00111427  0.00128957 ... -0.00162217  0.00036789
   0.00162217]
 [-0.01415143 -0.00170927  0.01417699 ...  0.00030785  0.00177389
   0.00039219]
 ...
 [-0.0006886  -0.00374275  0.00253903 ...  0.00058008  0.00148609
   0.00058008]
 [-0.00250947 -0.00082606  0.00250947 ...  0.00737149  0.00480103
   0.

   4.0842009e-05  7.4670788e-05]]
[[-2.78083887e-03 -5.71801886e-03  4.47326852e-03 ... -1.16639485e-05
   1.73610388e-04  4.98035108e-04]
 [ 6.41516130e-03 -1.18631008e-03  9.28013772e-03 ... -3.88786406e-03
   4.56996117e-04  1.03073986e-02]
 [ 3.23416060e-03 -1.63562899e-03  4.39421553e-03 ... -1.39631401e-03
   3.15020746e-03  4.13591368e-03]
 ...
 [-1.94507476e-03  1.45814847e-04  2.33480032e-03 ...  9.86800296e-04
   3.83041945e-04  1.04136812e-03]
 [-5.20847971e-03 -1.21006160e-03  8.12911522e-03 ...  3.30482749e-03
   6.93196524e-03  7.27533270e-03]
 [-5.32313425e-04 -4.53012995e-04  1.73744827e-03 ...  4.66728852e-05
   8.31382058e-05  4.66728852e-05]]
[[-3.0528603e-03 -4.3979785e-03  6.7196907e-03 ... -4.6855165e-04
   3.9845632e-04  5.8391708e-04]
 [ 4.7102277e-04  3.4993605e-04  5.5536878e-04 ... -4.2962849e-05
   3.0462013e-04  2.4272395e-04]
 [-1.2563785e-04  3.5207174e-04  3.4534468e-04 ...  6.2537252e-04
   5.4749507e-03  7.8439256e-03]
 ...
 [ 1.7049296e-04 -2.0875880e

   6.0621893e-04  9.0791791e-04]]
[[-0.0008233   0.00018861  0.0011009  ...  0.00018124  0.00493652
   0.0004315 ]
 [-0.00035372 -0.00106769  0.00037065 ...  0.00029578  0.00346261
   0.00170467]
 [-0.00288962  0.00188065  0.0030273  ...  0.00224062  0.00371644
   0.00454452]
 ...
 [-0.00405119  0.00020603  0.01198843 ... -0.00210989  0.01678103
   0.00356836]
 [ 0.00450939 -0.00072857  0.0096891  ... -0.00028219  0.00785345
   0.0003671 ]
 [-0.00172447  0.00531157  0.00502327 ... -0.00032067  0.00357921
   0.00034006]]
[[ 2.23275216e-04  1.80225854e-03  1.08286540e-03 ...  1.13920454e-04
   4.35596285e-03  4.10452858e-03]
 [-1.79704954e-03 -2.77206884e-04  2.07235548e-03 ...  1.50051579e-04
   1.56508666e-03  9.28704452e-04]
 [ 3.47175810e-04 -4.53506684e-04  6.60811027e-04 ...  2.75565617e-05
   3.23329167e-03  9.28824884e-04]
 ...
 [-3.56406928e-03 -8.79579317e-03  5.92333777e-03 ...  5.13489591e-03
   4.76892665e-03  7.51206372e-03]
 [-1.95922889e-03 -2.65785423e-03  2.05831975e-03

In [84]:

def BOVW(feature_descriptors, n_clusters = 15):
    print("Bag of visual words with {} clusters".format(n_clusters))
    #combined_features = np.vstack(np.array(feature_descriptors))
    combined_features = [point for image_keypoints in feature_descriptors for point in image_keypoints]
    print("Starting K-means training")
    kmeans_obj = KMeans(n_clusters=15, random_state=0).fit(combined_features)
    return kmeans_obj

def predict_bow_features(kmeans, descs):
    
    X = []
    for (i, desc) in enumerate(descs):
        if len(desc) == 0:
            continue
        result = kmeans.predict(desc)
        cluster_vector = [(result == i).sum() for i in range(0, kmeans.n_clusters)]
        X.append(cluster_vector)
    return np.array(X)
    

In [85]:

#from collections import Counter

kmeans = BOVW(image_surf_train)
x_train = predict_bow_features(kmeans, image_surf_train)
x_test = predict_bow_features(kmeans, image_surf_test)

'''
counter = Counter(result)
total=0
for val in counter.values():
    total += val
print(total)
plt.hist(result, bins=15)
'''

Bag of visual words with 15 clusters
Starting K-means training


'\ncounter = Counter(result)\ntotal=0\nfor val in counter.values():\n    total += val\nprint(total)\nplt.hist(result, bins=15)\n'

In [86]:


model = svm.SVC(max_iter=10000, C=100, gamma=0.5, probability=True)
model.fit(x_train, y_train)

/home/navya/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=100, probability=True, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [87]:

confidence_of_model = model.predict_proba(x_train)
confidence_example = np.amax(confidence_of_model, axis=1)
print(stats.describe(confidence_example))

DescribeResult(nobs=2274, minmax=(0.23437296377329328, 0.6757460779963016), mean=0.246368377688229, variance=0.0008601309958088052, skewness=4.510565588150267, kurtosis=36.724149386299246)


In [93]:
def get_accuracy(y_predict, y):
    accuracy = np.sum(y_predict == y).__float__() / float(len(y))
    confusion_matrix = metrics.confusion_matrix(y_predict, y, labels=[0, 1, 2, 3, 4, 5])
    return (accuracy, confusion_matrix)

In [94]:
 # Test SVM model

y_train_predict = np.array(model.predict(x_train))
y_test_predict = np.array(model.predict(x_test))
(train_accuracy, train_confusion_matrix) = get_accuracy(y_train_predict, y_train)
(test_accuracy, test_confusion_matrix) = get_accuracy(y_test_predict, y_test)
print('Train accuracy: ' + str(train_accuracy))
print('Train confusion matrix:')
print(train_confusion_matrix)
print('Test accuracy: ' + str(test_accuracy))
print('Test confusion matrix:')
print(test_confusion_matrix)

Train accuracy: 0.3935795954265611
Train confusion matrix:
[[103   0   0   3   2   0]
 [  2 106   0   0   1   0]
 [258 341 363 424 307  25]
 [  0   0   0 102   1   0]
 [  6   6   0   2 121   0]
 [  1   0   0   0   0 100]]
Test accuracy: 0.20948616600790515
Test confusion matrix:
[[ 0  0  0  1  0  0]
 [ 0  0  0  0  2  0]
 [32 48 47 62 42 12]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  6  0]
 [ 0  0  0  0  0  0]]


In [5]:
import cv2

In [6]:
cv2.__version__

'3.4.2'